import os
import sys
import subprocess
import xml.etree.ElementTree as ET
from datetime import datetime
import json

def run_tests(workspace_path: str, test_path: str):
    # Ensure working directory is workspace_path
    os.chdir(workspace_path)
    
    xml_report_path = "test_report.xml"
    md_report_path = "test_report.md"
    
    # 1. Run pytest command
    # Use python executable in the venv
    python_exe = os.path.join(workspace_path, ".venv", "Scripts", "python.exe")
    if not os.path.exists(python_exe):
        python_exe = "python" # fallback
        
    cmd = [python_exe, "-m", "pytest", f"--junitxml={xml_report_path}", test_path]
    print(f"Executing: {' '.join(cmd)}")
    
    # Run pytest (it might exit with non-zero if tests fail, which is normal)
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    # 2. Parse JUnit XML report
    if not os.path.exists(xml_report_path):
        print(f"Error: XML report not generated by pytest. Stderr: {result.stderr}")
        generate_error_report(md_report_path, f"Pytest 执行失败，未能生成 XML 报告。\n错误信息:\n{result.stderr or result.stdout}")
        return
        
    try:
        tree = ET.parse(xml_report_path)
        root = tree.getroot()
        
        # XML could have <testsuites> or <testsuite> at root
        total_tests = 0
        failures = 0
        errors = 0
        skipped = 0
        total_time = 0.0
        
        test_cases_list = []
        
        # Standard JUnit XML has <testsuites> or directly <testsuite>
        suites = []
        if root.tag == "testsuites":
            suites = list(root.findall("testsuite"))
            total_tests = int(root.attrib.get("tests", 0))
            failures = int(root.attrib.get("failures", 0))
            errors = int(root.attrib.get("errors", 0))
            total_time = float(root.attrib.get("time", 0.0))
        elif root.tag == "testsuite":
            suites = [root]
            total_tests = int(root.attrib.get("tests", 0))
            failures = int(root.attrib.get("failures", 0))
            errors = int(root.attrib.get("errors", 0))
            skipped = int(root.attrib.get("skipped", 0))
            total_time = float(root.attrib.get("time", 0.0))
            
        # Parse each test case
        for suite in suites:
            for case in suite.findall("testcase"):
                classname = case.attrib.get("classname", "")
                name = case.attrib.get("name", "")
                time_taken = float(case.attrib.get("time", 0.0))
                
                # Check outcome
                outcome = "✅ 通过 (Passed)"
                fail_msg = ""
                
                fail_el = case.find("failure")
                err_el = case.find("error")
                skip_el = case.find("skipped")
                
                if fail_el is not None:
                    outcome = "❌ 失败 (Failed)"
                    fail_msg = fail_el.text or fail_el.attrib.get("message", "测试未通过")
                elif err_el is not None:
                    outcome = "⚠️ 错误 (Error)"
                    fail_msg = err_el.text or err_el.attrib.get("message", "测试执行出错")
                elif skip_el is not None:
                    outcome = "⏭️ 跳过 (Skipped)"
                    fail_msg = skip_el.attrib.get("message", "跳过测试")
                    
                test_cases_list.append({
                    "classname": classname,
                    "name": name,
                    "time": time_taken,
                    "outcome": outcome,
                    "message": fail_msg
                })
                
        # If stats weren't parsed from root attribs, calculate them
        if total_tests == 0 and len(test_cases_list) > 0:
            total_tests = len(test_cases_list)
            failures = sum(1 for tc in test_cases_list if "Failed" in tc["outcome"])
            errors = sum(1 for tc in test_cases_list if "Error" in tc["outcome"])
            skipped = sum(1 for tc in test_cases_list if "Skipped" in tc["outcome"])
            total_time = sum(tc["time"] for tc in test_cases_list)
            
        passed = total_tests - failures - errors - skipped
        
        # 3. Generate Markdown Report
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        status_text = "🟢 正常 (PASSED)" if (failures == 0 and errors == 0) else "🔴 异常 (FAILED)"
        
        md_content = f"""# 🧪 Python 单元测试执行报告

*   **报告生成时间**: `{timestamp}`
*   **测试总体状态**: **{status_text}**
*   **测试目标路径**: `{test_path}`

---

## 📊 测试统计概要

| 统计指标 | 数值 | 占比 |
| :--- | :---: | :---: |
| **测试用例总数** | {total_tests} | 100% |
| **通过用例 (Passed)** | {passed} | {passed/total_tests*100:.1f}% |
| **失败用例 (Failed)** | {failures} | {failures/total_tests*100:.1f}% |
| **错误用例 (Errors)** | {errors} | {errors/total_tests*100:.1f}% |
| **跳过用例 (Skipped)** | {skipped} | {skipped/total_tests*100:.1f}% |
| **总计耗时 (Duration)** | `{total_time:.3f} 秒` | - |

---

## 📝 详细测试用例清单

| 测试模块/类 | 测试用例方法名 | 执行结果 | 耗时 |
| :--- | :--- | :---: | :---: |
"""
        for tc in test_cases_list:
            md_content += f"| `{tc['classname']}` | `{tc['name']}` | {tc['outcome']} | `{tc['time']:.3f}s` |\n"
            
        # Add failures detail section if any failures or errors exist
        failures_list = [tc for tc in test_cases_list if "Failed" in tc["outcome"] or "Error" in tc["outcome"]]
        if failures_list:
            md_content += "\n---\n\n## 🔍 失败用例详细堆栈\n\n"
            for fc in failures_list:
                md_content += f"### ❌ {fc['classname']}.{fc['name']}\n"
                md_content += f"*   **结果类型**: {fc['outcome']}\n"
                md_content += f"*   **异常原因及调用栈**:\n"
                md_content += f"```python\n{fc['message'].strip()}\n```\n\n"
                
        # Write to file
        with open(md_report_path, "w", encoding="utf-8") as f:
            f.write(md_content)
            
        print(f"Success: Test report written to {md_report_path}")
        
        # Write status marker JSON
        status_dir = os.path.join(workspace_path, ".agents", "status")
        os.makedirs(status_dir, exist_ok=True)
        status_file = os.path.join(status_dir, "test_passed.json")
        status_data = {
            "status": "passed" if (failures == 0 and errors == 0) else "failed",
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "total_tests": total_tests,
            "passed": passed,
            "failures": failures,
            "errors": errors,
            "skipped": skipped
        }
        with open(status_file, "w", encoding="utf-8") as f:
            json.dump(status_data, f, indent=2, ensure_ascii=False)
            
    except Exception as e:
        print(f"Exception parsing test results: {e}")
        generate_error_report(md_report_path, f"解析 XML 测试结果时发生异常:\n{str(e)}")
        
        # Write failed status marker JSON
        status_dir = os.path.join(workspace_path, ".agents", "status")
        os.makedirs(status_dir, exist_ok=True)
        status_file = os.path.join(status_dir, "test_passed.json")
        status_data = {
            "status": "failed",
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "error": str(e)
        }
        with open(status_file, "w", encoding="utf-8") as f:
            json.dump(status_data, f, indent=2, ensure_ascii=False)
        
    finally:
        # Clean up XML report file to keep workspace clean
        if os.path.exists(xml_report_path):
            os.remove(xml_report_path)

def generate_error_report(filepath: str, error_msg: str):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Write failed status marker JSON
    try:
        status_dir = os.path.join(".agents", "status")
        os.makedirs(status_dir, exist_ok=True)
        status_file = os.path.join(status_dir, "test_passed.json")
        status_data = {
            "status": "failed",
            "timestamp": timestamp,
            "error": error_msg[:200]
        }
        with open(status_file, "w", encoding="utf-8") as f:
            json.dump(status_data, f, indent=2, ensure_ascii=False)
    except Exception as e:
        print(f"Failed to write failed status marker: {e}")

    content = f"""# 🧪 Python 单元测试执行报告 (执行出错)

*   **报告生成时间**: `{timestamp}`
*   **测试总体状态**: 🔴 执行失败 (CRASHED)

---

## ❌ 错误信息

在执行测试或生成报告的过程中遇到了以下问题：

```
{error_msg}
```
"""
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python run_tests.py <workspace_path> <test_path>")
        sys.exit(1)
    run_tests(sys.argv[1], sys.argv[2])
